### ISSUE TITLE
Fonts too small under Wine in Ubuntu

### ISSUE THREAD

**Issue by erosman** [mmtrt/irfanview#11]
ref: Ubuntu 22.04
Is it possible to increase the menu fonts or DPI?

![image](https://user-images.githubusercontent.com/6458876/175091180-3a3888db-1761-4ae2-9bfb-cd670e2864c0.png)

**Comment by mmtrt** [comment]
Run `snap run irfanview.wine winecfg` then on `Graphics` tab there should be `DPI` setting change whatever suit you.

**Comment by erosman** [comment]
Great ..thank you.
_I have been using IrfanView for many years on Windows but now I have moved to Ubuntu._

Is it possible to set the icon sizes as well?
DPI only changed the font size.

![image](https://user-images.githubusercontent.com/6458876/175097441-a0beeebb-bbf3-453e-91a3-01a4cec54289.png)

**Comment by mmtrt** [comment]
Try this [link](https://irfanview-forum.de/forum/program/support/90961-version-4-57-toolbar-far-too-small?p=91201#post91201).

**Comment by erosman** [comment]
Awesome... thank you :+1:
