### ISSUE TITLE
Architecture unsupported

### ISSUE THREAD

**Issue by vaso123** [mmtrt/irfanview#3]
Hi!

I've installed the irfanview, and when I'd like to start it, I've got an error message:

Host architecture () unsupported.

What is this?

Using Ubuntu 18.04, 64-bit

**Comment by mmtrt** [comment]
working fine here, can you post info of this `snap list | grep -e wine -e irfan` and also try to remove snap data by removing dir `/home/$USER/snap/irfanview`

**Comment by vaso123** [comment]
Wine? Why do I need wine?

If I want to use wine, then I just download the .exe from the irfanview page. I thought this is a native linux port, there is nothing about wine in description or I just missed it.

**Comment by mmtrt** [comment]
My bad I did not add anything releated to wine in info so I've updated all my snaps title showing wine that should fix any confusion for new users.
