### ISSUE TITLE
Irfanview does not recognize folders or image files 

### ISSUE THREAD

**Issue by ineuw** [mmtrt/irfanview#7]
The file manager in Irfanview does not recognize folders and .MIME types unless it's located in the pseudo Z:\ partition which is the Linux $HOME folder.  How can I remedy this? How can I add other partitions to this scheme because I will not store data in the $HOME folder. I was directed here from the snapcraft forum and I doubt that WineHQ could help with snap.

**Comment by mmtrt** [comment]
if you are using data from mounted partitions then you have to connect this in order get the permission to use data in `irfanview`

`snap connect irfanview:removable-media`

**Comment by ineuw** [comment]
> if you are using data from mounted partitions then you have to connect this in order get the permission to use data in `irfanview`
> `snap connect irfanview:removable-media`
A big a thank you!!! My projects can move along.
